import React,{useState} from "react";
import {MessageSquare,PlusCircle,CheckCircle} from "lucide-react";
import Empty from "./Empty";
export default function Complaints({orders,complaints,setComplaints,adjustments,setAdjustments,types,statuses,resolutions,money}){
 const [open,setOpen]=useState(false); const [form,setForm]=useState({orderId:"",type:types[0],note:"",resolution:resolutions[4],amount:""});
 const submit=()=>{if(!form.orderId||!form.note.trim())return;const id="CMP-"+Date.now();setComplaints(cs=>[{id,...form,status:"Open",createdAt:new Date().toISOString()},...cs]);setOpen(false);setForm({orderId:"",type:types[0],note:"",resolution:resolutions[4],amount:""});};
 const resolve=c=>{const amount=Number(c.amount||0);setComplaints(cs=>cs.map(x=>x.id===c.id?{...x,status:"Resolved"}:x));if(amount>0&&c.resolution==="Refund")setAdjustments(as=>[{id:"ADJ-"+Date.now(),orderId:c.orderId,type:"Refund",amount,note:c.note,createdAt:new Date().toISOString()},...as]);};
 return <section className="content"><div className="section-head"><div><h2>Complaints & Feedback</h2><p>Link customer issues to orders and record resolutions locally.</p></div><button className="btn primary" onClick={()=>setOpen(v=>!v)}><PlusCircle size={16}/> New Complaint</button></div>
 {open&&<div className="panel complaint-form"><label>Order<select value={form.orderId} onChange={e=>setForm({...form,orderId:e.target.value})}><option value="">Select order</option>{orders.map(o=><option key={o.id}>{o.id}</option>)}</select></label><label>Issue<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{types.map(x=><option key={x}>{x}</option>)}</select></label><label>Details<textarea value={form.note} onChange={e=>setForm({...form,note:e.target.value})} placeholder="Describe the issue..."/></label><label>Resolution<select value={form.resolution} onChange={e=>setForm({...form,resolution:e.target.value})}>{resolutions.map(x=><option key={x}>{x}</option>)}</select></label><label>Refund/discount amount<input type="number" min="0" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><button className="btn primary" onClick={submit}>Save Complaint</button></div>}
 <div className="complaint-list">{complaints.length?complaints.map(c=><div className="panel complaint-card" key={c.id}><div><strong>{c.id} • {c.type}</strong><span>Order {c.orderId} • {new Date(c.createdAt).toLocaleString()}</span><p>{c.note}</p></div><div className="complaint-actions"><span className={"pill "+c.status.toLowerCase()}>{c.status}</span>{c.status!=="Resolved"&&c.status!=="Closed"&&<button className="btn" onClick={()=>resolve(c)}><CheckCircle size={15}/> Resolve</button>}</div></div>):<Empty icon={MessageSquare} title="No complaints" text="Customer issues linked to orders will appear here."/>}</div>
 <div className="panel"><div className="panel-head"><h3>Adjustments / Refunds</h3></div>{adjustments.length?adjustments.map(a=><div className="movement-row" key={a.id}><strong>{a.orderId}</strong><span>{a.type}</span><span>{money(a.amount)}</span><span>{new Date(a.createdAt).toLocaleDateString()}</span></div>):<div className="empty"><p>No adjustments recorded.</p></div>}</div>
 </section>;
}
