import React,{useState}from"react";
import {Plus,Users,Edit3,MapPin,Phone}from"lucide-react";
import Empty from "./Empty";
export default function Customers({customers,setCustomers,types}){
 const [q,setQ]=useState(""),[editing,setEditing]=useState(null),[form,setForm]=useState({name:"",phone:"",address:"",type:"Walk-in"});
 const open=(x=null)=>{setEditing(x?.id||"new");setForm({name:x?.name||"",phone:x?.phone||"",address:x?.address||"",type:x?.type||"Walk-in"})};
 const save=()=>{if(!form.name.trim())return alert("Customer name is required.");const clean={name:form.name.trim(),phone:form.phone.trim(),address:form.address.trim(),type:types.includes(form.type)?form.type:"Walk-in"};if(editing==="new")setCustomers(xs=>[...xs,{id:Date.now(),...clean,orders:0}]);else setCustomers(xs=>xs.map(x=>x.id===editing?{...x,...clean}:x));setEditing(null)};
 const list=customers.filter(x=>(x.name+" "+(x.phone||"")+" "+(x.address||"")).toLowerCase().includes(q.toLowerCase()));
 return <section className="content"><div className="section-head"><div><h2>Customers</h2><p>Save customer names, phone numbers and delivery addresses for faster ordering.</p></div><button className="primary dark" onClick={()=>open()}><Plus size={16}/> Add Customer</button></div>
 <div className="toolbar"><div className="search"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, phone or address..."/></div></div>
 {editing&&<div className="panel customer-editor"><div className="panel-head"><h3>{editing==="new"?"New Customer":"Edit Customer"}</h3><button className="btn" onClick={()=>setEditing(null)}>Cancel</button></div><div className="customer-form"><input placeholder="Customer name *" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input type="tel" placeholder="Phone number" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><textarea rows="2" placeholder="Delivery address / location" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{types.map(t=><option key={t}>{t}</option>)}</select><button className="btn primary" onClick={save}>Save Customer</button></div></div>}
 <div className="admin-grid">{list.length?list.map(x=><article className="admin-item" key={x.id}><div><span>{x.type}</span><strong>{x.name}</strong><small><Phone size={12}/> {x.phone||"No phone"} • <MapPin size={12}/> {x.address||"No delivery address"} • {x.orders||0} orders</small></div><button className="btn" onClick={()=>open(x)}><Edit3 size={13}/> Edit</button></article>):<Empty icon={Users} title="No customers" text="Add a customer when you need a saved profile."/>}</div></section>
}