import React,{useMemo,useState} from "react";import {AlertTriangle,PackagePlus,Trash2,RefreshCw,PlusCircle,ShoppingCart} from "lucide-react";import Empty from "./Empty";
export default function Inventory({ingredients,setIngredients,movements,setMovements,money}){const[q,setQ]=useState(""),[showLow,setShowLow]=useState(false),[form,setForm]=useState({id:"",qty:""}),[supplier,setSupplier]=useState("");const low=ingredients.filter(i=>i.stock<=i.reorderLevel),list=ingredients.filter(i=>(!showLow||i.stock<=i.reorderLevel)&&i.name.toLowerCase().includes(q.toLowerCase())),suppliers=useMemo(()=>[...new Set(ingredients.map(i=>i.supplier).filter(Boolean))],[ingredients]);
const addStock=()=>{const i=ingredients.find(x=>x.id===form.id),q=Number(form.qty);if(!i||q<=0)return;setIngredients(xs=>xs.map(x=>x.id===i.id?{...x,stock:x.stock+q}:x));setMovements(ms=>[{id:"MOV-"+Date.now(),ingredientId:i.id,type:"Purchase",qty:q,cost:i.cost*q,createdAt:new Date().toISOString()},...ms]);setForm({id:"",qty:""})};
const waste=i=>{const q=Number(prompt("Waste quantity for "+i.name+" ("+i.unit+")","1"));if(!q||q<=0||q>i.stock)return alert("Invalid waste quantity.");setIngredients(xs=>xs.map(x=>x.id===i.id?{...x,stock:x.stock-q}:x));setMovements(ms=>[{id:"MOV-"+Date.now(),ingredientId:i.id,type:"Waste",qty:q,cost:i.cost*q,createdAt:new Date().toISOString()},...ms])};
const adjust=i=>{const n=Number(prompt("Set actual stock for "+i.name,i.stock));if(!Number.isFinite(n)||n<0)return;const d=n-i.stock;setIngredients(xs=>xs.map(x=>x.id===i.id?{...x,stock:n}:x));if(d)setMovements(ms=>[{id:"MOV-"+Date.now(),ingredientId:i.id,type:"Adjustment",qty:Math.abs(d),cost:i.cost*Math.abs(d),direction:d>0?"IN":"OUT",createdAt:new Date().toISOString()},...ms])};
const rows=supplier?low.filter(i=>i.supplier===supplier):low;return <section className="content"><div className="section-head"><div><h2>Recipe-Level Inventory</h2><p>Purchases, waste, physical adjustments and reorder planning.</p></div><button className={showLow?"btn primary":"btn"} onClick={()=>setShowLow(v=>!v)}><AlertTriangle size={16}/>{showLow?"All Stock":"Low Stock ("+low.length+")"}</button></div>
<div className="inventory-toolbar"><input className="search" placeholder="Search ingredients..." value={q} onChange={e=>setQ(e.target.value)}/><select value={form.id} onChange={e=>setForm({...form,id:e.target.value})}><option value="">Ingredient to restock</option>{ingredients.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select><input className="small-input" type="number" min="0" step=".01" placeholder="Qty" value={form.qty} onChange={e=>setForm({...form,qty:e.target.value})}/><button className="btn primary" onClick={addStock}><PackagePlus size={16}/> Add Purchase</button></div>
<div className="inventory-grid">{list.map(i=><div className={"inventory-card "+(i.stock<=i.reorderLevel?"low":"")} key={i.id}><div><strong>{i.name}</strong><span>{i.supplier}</span></div><div className="inventory-number">{i.stock.toFixed(2)} {i.unit}</div><div className="inventory-meta"><span>Cost {money(i.cost)}/{i.unit}</span><span>Reorder {i.reorderLevel} {i.unit}</span></div><div className="inventory-actions">{i.stock<=i.reorderLevel&&<span className="status danger">Low stock</span>}<button className="icon-btn" onClick={()=>adjust(i)} title="Adjust physical stock"><PlusCircle size={16}/></button><button className="icon-btn" onClick={()=>waste(i)} title="Record waste"><Trash2 size={16}/></button></div></div>)}</div>
<div className="panel reorder-panel"><div className="panel-head"><h3><ShoppingCart size={16}/> Reorder Suggestions</h3><select value={supplier} onChange={e=>setSupplier(e.target.value)}><option value="">All suppliers</option>{suppliers.map(s=><option key={s}>{s}</option>)}</select></div>{rows.length?rows.map(i=><div className="movement-row" key={i.id}><strong>{i.name}</strong><span>{i.supplier}</span><span>{i.stock.toFixed(2)} {i.unit} now</span><span>Target {i.reorderLevel*2} {i.unit}</span><b>Order {Math.max(0,i.reorderLevel*2-i.stock).toFixed(2)}</b></div>):<Empty icon={ShoppingCart} title="Stock levels are healthy" text="No reorder suggestions for the selected supplier."/>}</div>
<div className="panel"><div className="panel-head"><h3>Recent Stock Movements</h3><RefreshCw size={17}/></div>{movements.slice(0,15).map(m=>{const i=ingredients.find(x=>x.id===m.ingredientId);return <div className="movement-row" key={m.id}><span>{m.type}</span><strong>{i?.name||m.ingredientId}</strong><span>{m.qty} {i?.unit||""}</span><span>{money(m.cost)}</span><small>{new Date(m.createdAt).toLocaleString()}</small></div>})}</div></section>}