import React,{useMemo,useState}from"react";
import {ShieldCheck,Clock3,ClipboardCheck,Calculator}from"lucide-react";
export default function Operations({staff,shifts,setShifts,auditLogs,money,activeStaffId,setActiveStaffId,orders=[],payments=[]}){
 const [opening,setOpening]=useState(""),[counted,setCounted]=useState("");
 const current=staff.find(s=>String(s.id)===String(activeStaffId)),active=shifts.find(s=>s.status==="Open");
 const shiftPayments=useMemo(()=>active?payments.filter(p=>p.status==="Paid"&&new Date(p.createdAt).getTime()>=new Date(active.openedAt).getTime()):[],[active,payments]);
 const totals=useMemo(()=>shiftPayments.reduce((a,p)=>{a[p.method]=(a[p.method]||0)+Number(p.amount||0);return a},{}),[shiftPayments]);
 const cashSales=totals.Cash||0, expectedCash=(Number(active?.openingCash)||0)+cashSales;
 const open=()=>{if(active||!current||current.role!=="Manager"&&current.role!=="Cashier"||!Number.isFinite(Number(opening))||Number(opening)<0)return;setShifts(xs=>[{id:"SHIFT-"+Date.now(),staffId:current.id,staffName:current.name,status:"Open",openedAt:new Date().toISOString(),openingCash:Number(opening)},...xs])};
 const close=()=>{if(!active)return;const n=Number(counted);if(!Number.isFinite(n)||n<0)return;const variance=n-expectedCash;setShifts(xs=>xs.map(s=>s.id===active.id?{...s,status:"Closed",closedAt:new Date().toISOString(),countedCash:n,expectedCash,variance,cashSales,mpesaSales:totals["M-Pesa"]||0,cardSales:totals.Card||0,bankSales:totals["Bank Transfer"]||0}:s))};
 return <section className="content"><div className="section-head"><div><h2>Operations & Controls</h2><p>Staff identity, cashier shifts, reconciliation and audit visibility.</p></div><span className="count">{active?"Shift open":"No open shift"}</span></div>
 <div className="admin-grid"><article className="admin-item"><div><span>Active staff</span><strong>{current?.name||"Not selected"}</strong><small>{current?.role||"Select a staff member"} • Used for operational actions.</small></div><select value={activeStaffId||""} onChange={e=>setActiveStaffId(e.target.value)}><option value="">Select staff</option>{staff.filter(s=>s.active!==false).map(s=><option key={s.id} value={s.id}>{s.name} • {s.role}</option>)}</select></article>
 <article className="admin-item"><div><span>Cashier shift</span><strong>{active?active.staffName:"Ready to open"}</strong><small>{active?"Opened "+new Date(active.openedAt).toLocaleString():"Only a Manager or Cashier can open a shift."}</small></div>{!active?<div className="head-actions"><input className="small-input" type="number" min="0" placeholder="Opening cash" value={opening} onChange={e=>setOpening(e.target.value)}/><button className="btn primary" disabled={!current||!["Manager","Cashier"].includes(current.role)} onClick={open}><Clock3 size={15}/> Open Shift</button></div>:<div className="head-actions"><input className="small-input" type="number" min="0" placeholder="Counted cash" value={counted} onChange={e=>setCounted(e.target.value)}/><button className="btn primary" onClick={close}><ClipboardCheck size={15}/> Close Shift</button></div>}</article></div>
 {active&&<div className="panel"><div className="panel-head"><h3><Calculator size={16}/> Shift Reconciliation</h3><span>{shiftPayments.length} payments</span></div><div className="movement-row"><strong>Opening cash</strong><span>{money(active.openingCash)}</span></div><div className="movement-row"><strong>Cash sales</strong><span>{money(cashSales)}</span></div><div className="movement-row"><strong>Expected cash</strong><span>{money(expectedCash)}</span></div><div className="movement-row"><strong>M-Pesa</strong><span>{money(totals["M-Pesa"]||0)}</span></div><div className="movement-row"><strong>Card</strong><span>{money(totals.Card||0)}</span></div><div className="movement-row"><strong>Bank Transfer</strong><span>{money(totals["Bank Transfer"]||0)}</span></div></div>}
 <div className="panel"><div className="panel-head"><h3><ShieldCheck size={16}/> Audit Log</h3><span>{auditLogs.length} events</span></div>{auditLogs.length?auditLogs.slice(0,30).map(x=><div className="movement-row" key={x.id}><strong>{x.action}</strong><span>{x.staffName||"System"}</span><span>{x.entityId||"—"}</span><small>{x.details||""} • {new Date(x.createdAt).toLocaleString()}</small></div>):<div className="empty"><p>No audit events yet.</p></div>}</div>
 </section>}
