import React,{useMemo,useState}from"react";
import {ShieldCheck,Clock3,ClipboardCheck}from"lucide-react";
export default function Operations({staff,shifts,setShifts,auditLogs,money,activeStaffId,setActiveStaffId}){const staffId=activeStaffId,[opening,setOpening]=useState(""),[counted,setCounted]=useState("");
 const active=shifts.find(s=>s.status==="Open");const current=staff.find(s=>String(s.id)===String(staffId));
 const open=()=>{if(active||!current||Number(opening)<0)return;setShifts(xs=>[{id:"SHIFT-"+Date.now(),staffId:current.id,staffName:current.name,status:"Open",openedAt:new Date().toISOString(),openingCash:Number(opening),cashSales:0},...xs])};
 const close=()=>{if(!active)return;const n=Number(counted);if(!Number.isFinite(n)||n<0)return;setShifts(xs=>xs.map(s=>s.id===active.id?{...s,status:"Closed",closedAt:new Date().toISOString(),countedCash:n,variance:n-(Number(s.openingCash)||0)+(Number(s.cashSales)||0)}:s))};
 return <section className="content"><div className="section-head"><div><h2>Operations & Controls</h2><p>Staff identity, cashier shifts and audit visibility.</p></div><span className="count">{active?"Shift open":"No open shift"}</span></div>
 <div className="admin-grid"><article className="admin-item"><div><span>Active staff</span><strong>{current?.name||"Not selected"}</strong><small>Used as the operational identity for the next transactions.</small></div><select value={staffId} onChange={e=>setActiveStaffId(e.target.value)}><option value="">Select staff</option>{staff.filter(s=>s.active!==false).map(s=><option key={s.id} value={s.id}>{s.name} • {s.role}</option>)}</select></article>
 <article className="admin-item"><div><span>Cashier shift</span><strong>{active?active.staffName:"Ready to open"}</strong><small>{active?"Opened "+new Date(active.openedAt).toLocaleString():"Set opening cash before starting."}</small></div>{!active?<div className="head-actions"><input className="small-input" type="number" min="0" placeholder="Opening cash" value={opening} onChange={e=>setOpening(e.target.value)}/><button className="btn primary" disabled={!current} onClick={open}><Clock3 size={15}/> Open Shift</button></div>:<div className="head-actions"><input className="small-input" type="number" min="0" placeholder="Counted cash" value={counted} onChange={e=>setCounted(e.target.value)}/><button className="btn primary" onClick={close}><ClipboardCheck size={15}/> Close Shift</button></div>}</article></div>
 <div className="panel"><div className="panel-head"><h3><ShieldCheck size={16}/> Audit Log</h3><span>{auditLogs.length} events</span></div>{auditLogs.length?auditLogs.slice(0,30).map(x=><div className="movement-row" key={x.id}><strong>{x.action}</strong><span>{x.staffName||"System"}</span><span>{x.entityId||"—"}</span><small>{new Date(x.createdAt).toLocaleString()}</small></div>):<div className="empty"><p>No audit events yet.</p></div>}</div>
 </section>}