import React,{useState} from "react";
import {ClipboardList,Edit3,Split,ArrowRightLeft} from "lucide-react";
import Empty from "./Empty";
export function OrderCard({order,update,money,onEdit,onSplit,onVoid,onTransfer}){
 const [splitOpen,setSplitOpen]=useState(false),[itemKey,setItemKey]=useState(order.items.find(x=>x.qty>1)?.key||""),[qty,setQty]=useState(1);
 const item=order.items.find(x=>x.key===itemKey);
 const doSplit=()=>{if(!item||qty<1||qty>=item.qty)return;onSplit(order,itemKey,Number(qty));setSplitOpen(false)};
 return <article className="order-card"><div className="order-title"><div><strong>{order.id}</strong><span>{order.channel}{order.table?" • "+order.table:""}{order.customerName?" • "+order.customerName:""}{order.splitBill?" • Split bill":""} • {new Date(order.createdAt).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</span></div><span className={"pill "+order.status.toLowerCase().replaceAll(" ","-")}>{order.status}</span></div>
  <div className="order-items">{order.items.map(x=><div key={x.key}><span>{x.qty} × {x.name}{x.seat?" • S"+x.seat:""}</span><small>{x.modifier?.name||x.modifier||"Standard"}</small></div>)}</div>
  {splitOpen&&<div className="split-editor"><select value={itemKey} onChange={e=>{setItemKey(e.target.value);setQty(1)}}>{order.items.filter(x=>x.qty>1).map(x=><option key={x.key} value={x.key}>{x.name} ({x.qty} available)</option>)}</select><input type="number" min="1" max={Math.max(1,(item?.qty||1)-1)} value={qty} onChange={e=>setQty(Math.max(1,Number(e.target.value)||1))}/><button onClick={doSplit}>Create split</button><button className="ghost" onClick={()=>setSplitOpen(false)}>Cancel</button></div>}
  <div className="order-foot"><b>{money(order.total)}</b><div className="order-actions">{order.status==="Placed"&&<button onClick={()=>onEdit(order)}><Edit3 size={12}/> Edit</button>}{order.status==="Placed"&&order.items.some(x=>x.qty>1)&&<button onClick={()=>setSplitOpen(v=>!v)}><Split size={12}/> Split items</button>}{order.channel==="Dine In"&&order.status!=="Served/Out for Delivery"&&!order.splitBill&&<button onClick={()=>onTransfer(order)}><ArrowRightLeft size={12}/> Transfer</button>}{order.status==="Placed"&&<button onClick={()=>update(order.id,"In Prep")}>Start Prep</button>}{order.status==="In Prep"&&<button onClick={()=>update(order.id,"Ready")}>Mark Ready</button>}{order.status==="Ready"&&<button onClick={()=>update(order.id,"Served/Out for Delivery")}>Complete</button>}{order.status!=="Voided"&&<button className="danger-action" onClick={()=>onVoid(order.id)}>Void</button>}</div></div></article>}
export default function Orders({orders,update,money,onEdit,onSplit,onVoid,onTransfer}){return <section className="content"><div className="section-head"><div><h2>Order Queue</h2><p>Edit placed orders, split item quantities and transfer dine-in orders.</p></div><span className="count">{orders.length} total</span></div><div className="order-list">{orders.length?orders.map(o=><OrderCard key={o.id} order={o} update={update} money={money} onEdit={onEdit} onSplit={onSplit} onVoid={onVoid} onTransfer={onTransfer}/>):<Empty icon={ClipboardList} title="No orders" text="New POS orders will appear here."/>}</div></section>}
