import React,{useMemo,useState} from "react";
import {CreditCard,Receipt,RotateCcw} from "lucide-react";
import Empty from "./Empty";
export default function Payments({orders,payments,setPayments,money}){
 const [selected,setSelected]=useState(""); const [method,setMethod]=useState("Cash"); const [amount,setAmount]=useState(""); const [split,setSplit]=useState(1);
 const unpaid=orders.filter(o=>o.total>0);
 const selectedOrder=orders.find(o=>o.id===selected);
 const paid=payments.filter(p=>p.orderId===selected).reduce((s,p)=>s+(p.status==="Refunded"?-p.amount:p.amount),0);
 const balance=selectedOrder?Math.max(0,selectedOrder.total-paid):0;
 const pay=()=>{const n=Number(amount||balance);if(!selectedOrder||n<=0||n>balance)return;setPayments(ps=>[{id:"PAY-"+Date.now(),orderId:selectedOrder.id,amount:n,method,status:"Paid",createdAt:new Date().toISOString()},...ps]);setAmount("");};
 const splitAmounts=useMemo(()=>selectedOrder?Array.from({length:Math.max(1,Number(split)||1)},()=>Math.round((balance/Math.max(1,Number(split)||1))*100)/100):[],[selectedOrder,balance,split]);
 const paySplit=()=>{if(!selectedOrder||splitAmounts.length<2)return;setPayments(ps=>[...splitAmounts.map((n,i)=>({id:"PAY-"+Date.now()+"-"+i,orderId:selectedOrder.id,amount:n,method,status:"Paid",createdAt:new Date().toISOString()})),...ps]);setSplit(1);};
 return <section className="content"><div className="section-head"><div><h2>Billing & Payments</h2><p>Record local payments, balances and split bills. No external payment gateway is connected.</p></div></div>
 <div className="payment-layout"><div className="panel"><div className="panel-head"><h3>Orders to Settle</h3></div><div className="list">{unpaid.length?unpaid.map(o=>{const p=payments.filter(x=>x.orderId===o.id).reduce((s,x)=>s+(x.status==="Refunded"?-x.amount:x.amount),0),b=Math.max(0,o.total-p);return <button className="payment-order" key={o.id} onClick={()=>setSelected(o.id)}><span><strong>{o.id}</strong><small>{o.channel}{o.table?" • "+o.table:""}</small></span><b>{money(b)}</b></button>}):<Empty icon={Receipt} title="No orders" text="Orders created in the POS appear here."/>}</div></div>
 <div className="panel payment-box">{selectedOrder?<><div className="panel-head"><h3>{selectedOrder.id}</h3><strong>{money(balance)} balance</strong></div><div className="payment-form"><label>Payment method<select value={method} onChange={e=>setMethod(e.target.value)}><option>Cash</option><option>M-Pesa</option><option>Card</option><option>Bank Transfer</option></select></label><label>Amount<input type="number" min="0" step="0.01" max={balance} value={amount} onChange={e=>setAmount(e.target.value)} placeholder={String(balance)}/></label><button className="btn primary" onClick={pay} disabled={!balance}><CreditCard size={16}/> Record Payment</button></div><div className="split-box"><strong>Split bill</strong><div><input type="number" min="2" max="10" value={split} onChange={e=>setSplit(e.target.value)}/><span>{splitAmounts.length?splitAmounts.map((n,i)=><small key={i}>Part {i+1}: {money(n)}</small>):null}</span></div><button className="btn" onClick={paySplit} disabled={balance<=0||Number(split)<2}><Receipt size={15}/> Pay equally</button></div><div className="panel-head"><h3>Payment History</h3><RotateCcw size={16}/></div>{payments.filter(p=>p.orderId===selected).map(p=><div className="movement-row" key={p.id}><strong>{p.method}</strong><span>{money(p.amount)}</span><span>{p.status}</span></div>)}</>:<Empty icon={CreditCard} title="Select an order" text="Choose an order to record payment or split its bill."/>}</div></div>
 </section>;
}
