import React,{useMemo,useState} from "react";
import {Search,Plus,Minus,Trash2,ReceiptText,Utensils,Bike,ShoppingBag,UserRound,Armchair} from "lucide-react";
import Empty from "./Empty";

export default function POS({activeStaffId,staff,setActiveStaffId,menu,categories,modifiers,cart,addItem,changeQty,removeCart,placeOrder,channel,setChannel,selectedTable,setSelectedTable,tables,money,customers,setCustomerId,customerId,editingOrderId,cancelEdit}){
 const [search,setSearch]=useState(""); const [category,setCategory]=useState("All"); const [modifier,setModifier]=useState("standard"); const [seat,setSeat]=useState(null);
 const tableSeats=selectedTable?.seatState||Array.from({length:selectedTable?.seats||0},(_,i)=>({seat:i+1,occupied:false}));
 const filtered=useMemo(()=>menu.filter(x=>x.active!==false&&(category==="All"||x.category===category)&&x.name.toLowerCase().includes(search.toLowerCase())),[menu,category,search]);
 const selectedModifier=modifiers.find(x=>x.id===modifier)||modifiers[0]; const total=cart.reduce((s,x)=>s+x.price*x.qty,0);
 const add=(item)=>addItem(item,selectedModifier,seat);
 return <section className="content pos-layout"><div className="pos-main">
  <div className="toolbar"><div className="search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search menu..."/></div><div className="chips"><button className={category==="All"?"chip active":"chip"} onClick={()=>setCategory("All")}>All</button>{categories.map(c=><button className={category===c?"chip active":"chip"} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div></div>
  <div className="modifier-bar"><span>Modifier</span>{modifiers.map(m=><button key={m.id} className={modifier===m.id?"modifier active":"modifier"} onClick={()=>setModifier(m.id)}>{m.name}{m.price?" +"+money(m.price):""}</button>)}</div>
  {channel==="Dine In"&&selectedTable&&<div className="seat-bar"><div className="seat-label"><Armchair size={14}/> Seat</div><button className={seat===null?"seat active":"seat"} onClick={()=>setSeat(null)}>Unassigned</button>{tableSeats.map(s=><button key={s.seat} className={seat===s.seat?"seat active":"seat"} onClick={()=>setSeat(s.seat)}>S{s.seat}{s.occupied?" • used":""}</button>)}</div>}
  <div className="menu-grid">{filtered.map(item=><button className="menu-item" onClick={()=>add(item)} key={item.id}><span className="menu-category">{item.category}</span><strong>{item.name}</strong><b>{money(item.price+selectedModifier.price)}</b><span className="add"><Plus size={14}/></span></button>)}</div>
 </div>
 <aside className="cart-panel">{editingOrderId&&<div className="edit-banner">Editing {editingOrderId}<button onClick={cancelEdit}>Cancel</button></div>}
  <div className="cart-head"><div><h3>{editingOrderId?"Edit Order":"Current Order"}</h3><small>{cart.reduce((s,x)=>s+x.qty,0)} items{selectedTable?" • "+selectedTable.name:""}</small></div><ReceiptText size={20}/></div>
  <select className="select" value={activeStaffId||""} onChange={e=>setActiveStaffId(e.target.value)}><option value="">Select staff</option>{staff.filter(s=>s.active!==false).map(s=><option key={s.id} value={s.id}>{s.name} • {s.role}</option>)}</select><div className="channel-tabs">{["Dine In","Take Away","Delivery"].map(c=><button className={channel===c?"active":""} onClick={()=>{setChannel(c);if(c!=="Dine In")setSeat(null)}} key={c}>{c==="Dine In"?<Utensils size={14}/>:c==="Delivery"?<Bike size={14}/>:<ShoppingBag size={14}/>} {c}</button>)}</div>
  {channel==="Dine In"&&<><select className="select" value={selectedTable?.id||""} onChange={e=>{const t=tables.find(x=>x.id===Number(e.target.value))||null;setSelectedTable(t);setSeat(null)}}><option value="">Select table</option>{tables.filter(t=>t.status==="Vacant"||(selectedTable&&t.id===selectedTable.id)||t.orderId===editingOrderId).map(t=><option value={t.id} key={t.id}>{t.name} • {t.seats} seats{t.mergedGroupId?" • merged":""}</option>)}</select>
   <select className="select" value={customerId||""} onChange={e=>setCustomerId(e.target.value||null)}><option value="">Walk-in customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name} • {c.phone}</option>)}</select></>}
  {channel!=="Dine In"&&<select className="select" value={customerId||""} onChange={e=>setCustomerId(e.target.value||null)}><option value="">Walk-in customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name} • {c.phone}</option>)}</select>}
  <div className="cart-items">{cart.length?cart.map(x=><div className="cart-row" key={x.key}><div><strong>{x.name}</strong><small>{x.modifier?.name||x.modifier||"Standard"}{x.seat?" • Seat "+x.seat:""}</small></div><b>{money(x.price*x.qty)}</b><div className="qty"><button onClick={()=>changeQty(x.key,-1)}><Minus size={12}/></button><span>{x.qty}</span><button onClick={()=>changeQty(x.key,1)}><Plus size={12}/></button></div><button className="icon-btn danger" onClick={()=>removeCart(x.key)}><Trash2 size={14}/></button></div>):<Empty icon={ShoppingBag} title="Cart is empty" text="Tap a menu item to add it."/>}</div>
  <div className="cart-total"><span>Total</span><strong>{money(total)}</strong></div><button className="checkout" disabled={!cart.length||!activeStaffId||channel==="Dine In"&&!selectedTable} onClick={placeOrder}>{editingOrderId?"Save Changes":"Place Order"}</button>
 </aside></section>
}