import React,{useMemo,useState} from "react";
import {Search,Plus,Minus,Trash2,ReceiptText,Utensils,Bike,ShoppingBag,UserRound,Armchair} from "lucide-react";
import Empty from "./Empty";

export default function POS({discount,setDiscount,applyDiscount,deliveryInfo,setDeliveryInfo,activeStaffId,staff,setActiveStaffId,menu,categories,modifiers,cart,addItem,changeQty,removeCart,placeOrder,channel,setChannel,selectedTable,setSelectedTable,tables,money,customers,setCustomerId,customerId,editingOrderId,cancelEdit}){
 const [search,setSearch]=useState(""); const [category,setCategory]=useState("All"); const [modifier,setModifier]=useState("standard"); const [seat,setSeat]=useState(null);
 const tableSeats=selectedTable?.seatState||Array.from({length:selectedTable?.seats||0},(_,i)=>({seat:i+1,occupied:false}));
 const filtered=useMemo(()=>menu.filter(x=>x.active!==false&&(category==="All"||x.category===category)&&x.name.toLowerCase().includes(search.toLowerCase())),[menu,category,search]);
 const selectedModifier=modifiers.find(x=>x.id===modifier)||modifiers[0]; const subtotal=cart.reduce((s,x)=>s+x.price*x.qty,0); const discountAmount=Math.min(subtotal,discount?.type==="percent"?subtotal*Math.min(100,Math.max(0,Number(discount?.value)||0))/100:Math.max(0,Number(discount?.value)||0)); const total=Math.max(0,subtotal-discountAmount);
 const add=(item)=>addItem(item,selectedModifier,seat);
 return <section className="content pos-layout"><div className="pos-main">
  <div className="toolbar"><div className="search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search menu..."/></div><div className="chips"><button className={category==="All"?"chip active":"chip"} onClick={()=>setCategory("All")}>All</button>{categories.map(c=><button className={category===c?"chip active":"chip"} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div></div>
  <div className="modifier-bar"><span>Modifier</span>{modifiers.map(m=><button key={m.id} className={modifier===m.id?"modifier active":"modifier"} onClick={()=>setModifier(m.id)}>{m.name}{m.price?" +"+money(m.price):""}</button>)}</div>
  {channel==="Dine In"&&selectedTable&&<div className="seat-bar"><div className="seat-label"><Armchair size={14}/> Seat</div><button className={seat===null?"seat active":"seat"} onClick={()=>setSeat(null)}>Unassigned</button>{tableSeats.map(s=><button key={s.seat} className={seat===s.seat?"seat active":"seat"} onClick={()=>setSeat(s.seat)}>S{s.seat}{s.occupied?" • used":""}</button>)}</div>}
  <div className="menu-grid">{filtered.map(item=><button className="menu-item" onClick={()=>add(item)} key={item.id}><span className="menu-category">{item.category}</span><strong>{item.name}</strong><b>{money(item.price+selectedModifier.price)}</b><span className="add"><Plus size={14}/></span></button>)}</div>
 </div>
 <aside className="cart-panel">{editingOrderId&&<div className="edit-banner">Editing {editingOrderId}<button onClick={cancelEdit}>Cancel</button></div>}
  <div className="cart-head"><div><h3>{editingOrderId?"Edit Order":"Current Order"}</h3><small>{cart.reduce((s,x)=>s+x.qty,0)} items{selectedTable?" • "+selectedTable.name:""}</small></div><ReceiptText size={20}/></div>
  <select className="select" value={activeStaffId||""} onChange={e=>setActiveStaffId(e.target.value)}><option value="">Select staff</option>{staff.filter(s=>s.active!==false).map(s=><option key={s.id} value={s.id}>{s.name} • {s.role}</option>)}</select><div className="channel-tabs">{["Dine In","Take Away","Delivery"].map(c=><button className={channel===c?"active":""} onClick={()=>{setChannel(c);if(c!=="Dine In")setSeat(null)}} key={c}>{c==="Dine In"?<Utensils size={14}/>:c==="Delivery"?<Bike size={14}/>:<ShoppingBag size={14}/>} {c}</button>)}</div>
  {channel==="Dine In"&&<><select className="select" value={selectedTable?.id||""} onChange={e=>{const t=tables.find(x=>x.id===Number(e.target.value))||null;setSelectedTable(t);setSeat(null)}}><option value="">Select table</option>{tables.filter(t=>t.status==="Vacant"||(selectedTable&&t.id===selectedTable.id)||t.orderId===editingOrderId).map(t=><option value={t.id} key={t.id}>{t.name} • {t.seats} seats{t.mergedGroupId?" • merged":""}</option>)}</select>
   <select className="select" value={customerId||""} onChange={e=>setCustomerId(e.target.value||null)}><option value="">Walk-in customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name} • {c.phone}</option>)}</select></>}
  {channel!=="Dine In"&&<select className="select" value={customerId||""} onChange={e=>{const id=e.target.value||null;const c=customers.find(x=>String(x.id)===String(id));setCustomerId(id);if(c)setDeliveryInfo({name:c.name||"",phone:c.phone||"",address:c.address||""})}}><option value="">Walk-in customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name} • {c.phone||"No phone"}</option>)}</select>}{channel==="Delivery"&&<div className="delivery-info"><div className="delivery-info-head"><div><strong>Delivery Information</strong><small>Required for dispatch</small></div><Bike size={17}/></div><input className="select" placeholder="Customer name" value={deliveryInfo?.name||""} onChange={e=>setDeliveryInfo({...deliveryInfo,name:e.target.value})}/><input className="select" type="tel" placeholder="Phone number" value={deliveryInfo?.phone||""} onChange={e=>setDeliveryInfo({...deliveryInfo,phone:e.target.value})}/><textarea className="delivery-address" rows="2" placeholder="Delivery address / location details" value={deliveryInfo?.address||""} onChange={e=>setDeliveryInfo({...deliveryInfo,address:e.target.value})}/><small className="delivery-required">Name, phone and address are required before placing a delivery order.</small></div>}}
  <div className="cart-items">{cart.length?cart.map(x=><div className="cart-row" key={x.key}><div><strong>{x.name}</strong><small>{x.modifier?.name||x.modifier||"Standard"}{x.seat?" • Seat "+x.seat:""}</small></div><b>{money(x.price*x.qty)}</b><div className="qty"><button onClick={()=>changeQty(x.key,-1)}><Minus size={12}/></button><span>{x.qty}</span><button onClick={()=>changeQty(x.key,1)}><Plus size={12}/></button></div><button className="icon-btn danger" onClick={()=>removeCart(x.key)}><Trash2 size={14}/></button></div>):<Empty icon={ShoppingBag} title="Cart is empty" text="Tap a menu item to add it."/>}</div>
  <div className="discount-box">
    <div className="discount-head"><strong>Discount</strong><small>Manager approval above 10% or KSh 500</small></div>
    <div className="discount-controls"><select value={discount?.type||"percent"} onChange={e=>setDiscount({...discount,type:e.target.value})}><option value="percent">Percent %</option><option value="fixed">Fixed KSh</option></select><input type="number" min="0" step="0.01" max={discount?.type==="percent"?100:subtotal} value={discount?.value||0} onChange={e=>setDiscount({...discount,value:e.target.value})}/><input placeholder="Reason required" value={discount?.reason||""} onChange={e=>setDiscount({...discount,reason:e.target.value})}/><button className="btn" onClick={()=>applyDiscount(discount)} disabled={!subtotal}>Apply</button></div>
    {discountAmount>0&&<small className="discount-applied">Discount: -{money(discountAmount)}{discount?.approvedByName?" • Approved by "+discount.approvedByName:""}</small>}
  </div>
  <div className="cart-total"><span>Subtotal</span><strong>{money(subtotal)}</strong></div><div className="cart-total"><span>Discount</span><strong>-{money(discountAmount)}</strong></div><div className="cart-total"><span>Total</span><strong>{money(total)}</strong></div><button className="checkout" disabled={!cart.length||!activeStaffId||channel==="Dine In"&&!selectedTable||channel==="Delivery"&&(!deliveryInfo?.name?.trim()||!deliveryInfo?.phone?.trim()||!deliveryInfo?.address?.trim())} onClick={placeOrder}>{editingOrderId?"Save Changes":"Place Order"}</button>
 </aside></section>
}