import React,{useEffect,useState} from "react";
import {Settings} from "lucide-react";
import Sidebar from "./components/Sidebar";import Topbar from "./components/Topbar";import Dashboard from "./components/Dashboard";import POS from "./components/POS";import Tables from "./components/Tables";import Orders from "./components/Orders";import Kitchen from "./components/Kitchen";import Delivery from "./components/Delivery";import MenuManager from "./components/MenuManager";import Staff from "./components/Staff";import Customers from "./components/Customers";import Inventory from "./components/Inventory";import Payments from "./components/Payments";import Complaints from "./components/Complaints";import Analytics from "./components/Analytics";import StaffPerformance from "./components/StaffPerformance";
import {initialStaff,staffRoles} from "./data/staff";import {initialCustomers,customerTypes} from "./data/customers";import {initialRiders,riderStatuses} from "./data/delivery";import {menuItems,categories,modifiers} from "./data/menu";import {initialTables,tableStatuses} from "./data/tables";import {loadStore,saveStore} from "./lib/storage";import {orderStatuses} from "./data/workflows";import {initialIngredients} from "./data/inventory";import {initialRecipes} from "./data/recipes";import {initialPayments} from "./data/payments";import {initialComplaints,initialAdjustments,complaintTypes,complaintStatuses,resolutions} from "./data/complaints";import {initialShifts} from "./data/shifts";import "./styles.css";
const money=n=>"KSh "+Number(n||0).toLocaleString("en-KE",{minimumFractionDigits:2,maximumFractionDigits:2});
const normaliseTables=ts=>ts.map(t=>({...t,seatState:t.seatState?.length?t.seatState:Array.from({length:t.seats||4},(_,i)=>({seat:i+1,occupied:false}))}));
export default function App(){
 const [collapsed,setCollapsed]=useState(false),[active,setActive]=useState("Dashboard");const [menu,setMenu]=useState(()=>loadStore("restaurant-menu",menuItems)),[tables,setTables]=useState(()=>normaliseTables(loadStore("restaurant-tables",initialTables))),[orders,setOrders]=useState(()=>loadStore("restaurant-orders",[]));
 const [cart,setCart]=useState([]),[channel,setChannel]=useState("Dine In"),[selectedTable,setSelectedTable]=useState(null),[customerId,setCustomerId]=useState(null),[editingOrderId,setEditingOrderId]=useState(null);
 const [staff,setStaff]=useState(()=>loadStore("restaurant-staff",initialStaff)),[customers,setCustomers]=useState(()=>loadStore("restaurant-customers",initialCustomers)),[riders,setRiders]=useState(()=>loadStore("restaurant-riders",initialRiders));
 const [ingredients,setIngredients]=useState(()=>loadStore("restaurant-ingredients",initialIngredients)),[recipes]=useState(()=>loadStore("restaurant-recipes",initialRecipes)),[movements,setMovements]=useState(()=>loadStore("restaurant-stock-movements",[]));const [payments,setPayments]=useState(()=>loadStore("restaurant-payments",initialPayments)),[complaints,setComplaints]=useState(()=>loadStore("restaurant-complaints",initialComplaints)),[adjustments,setAdjustments]=useState(()=>loadStore("restaurant-adjustments",initialAdjustments)),[shifts,setShifts]=useState(()=>loadStore("restaurant-shifts",initialShifts));
 [[menu,"restaurant-menu"],[tables,"restaurant-tables"],[orders,"restaurant-orders"],[staff,"restaurant-staff"],[customers,"restaurant-customers"],[riders,"restaurant-riders"],[ingredients,"restaurant-ingredients"],[recipes,"restaurant-recipes"],[movements,"restaurant-stock-movements"],[payments,"restaurant-payments"],[complaints,"restaurant-complaints"],[adjustments,"restaurant-adjustments"],[shifts,"restaurant-shifts"]].forEach(([v,k])=>useEffect(()=>saveStore(k,v),[v]));
 const todaySales=orders.filter(o=>o.status===orderStatuses[3]).reduce((s,o)=>s+Number(o.total||0),0),occupied=tables.filter(t=>t.status!=="Vacant").length,lowStock=ingredients.filter(i=>i.stock<=i.reorderLevel).length,openOrders=orders.filter(o=>o.status!==orderStatuses[3]).length;
 const reqs=items=>{const r={};items.forEach(x=>(recipes[x.id]||[]).forEach(v=>r[v.ingredientId]=(r[v.ingredientId]||0)+v.qty*x.qty));return r};
 const planFIFO=(requirements,base=ingredients)=>{const allocations=[],short=[];Object.entries(requirements).forEach(([ingredientId,needed])=>{const i=base.find(x=>x.id===ingredientId);if(!i){short.push([ingredientId,needed]);return}let remaining=needed;const batches=[...(i.batches||[])].map(b=>({...b})).sort((a,b)=>new Date(a.receivedAt||0)-new Date(b.receivedAt||0));const represented=batches.reduce((s,b)=>s+Number(b.remaining||0),0);if(represented<i.stock)batches.unshift({id:"OPENING-"+ingredientId,batchNo:"OPENING",remaining:i.stock-represented,cost:i.cost,supplier:i.supplier,receivedAt:"1970-01-01T00:00:00.000Z"});batches.forEach(b=>{if(remaining<=0)return;const take=Math.min(remaining,Number(b.remaining||0));if(take>0){allocations.push({ingredientId,batchId:b.id,batchNo:b.batchNo,qty:take,cost:Number(b.cost||i.cost)});remaining-=take}});if(remaining>0)short.push([ingredientId,remaining])});return{allocations,short}};
 const applyConsumption=(allocations,direction,type,orderId)=>{setIngredients(xs=>xs.map(i=>{const mine=allocations.filter(a=>a.ingredientId===i.id);if(!mine.length)return i;let batches=[...(i.batches||[])];mine.forEach(a=>{let b=batches.find(x=>x.id===a.batchId);if(!b&&a.batchNo==="OPENING")b={id:a.batchId,batchNo:"OPENING",qty:i.stock,remaining:i.stock,cost:i.cost,supplier:i.supplier,receivedAt:"1970-01-01T00:00:00.000Z"},batches=[b,...batches];if(b)b.remaining=Math.max(0,Number(b.remaining||0)+direction*a.qty)});return{...i,stock:i.stock+direction*mine.reduce((s,a)=>s+a.qty,0),batches}}));setMovements(ms=>allocations.map(a=>({id:"MOV-"+Date.now()+"-"+Math.random().toString(36).slice(2,7),ingredientId:a.ingredientId,type,qty:a.qty,cost:a.qty*a.cost,batchNo:a.batchNo,orderId,createdAt:new Date().toISOString()})).concat(ms))};
 const restoreConsumption=(allocations,orderId)=>applyConsumption(allocations,1,"Sale Reversal",orderId);
 function addItem(item,modifier=modifiers[0],seat=null){const m=typeof modifier==="string"?modifiers.find(x=>x.name===modifier)||modifiers[0]:modifier;setCart(c=>{const key=item.id+"-"+m.id+"-"+(seat||"U"),f=c.find(x=>x.key===key);return f?c.map(x=>x.key===key?{...x,qty:x.qty+1}:x):[...c,{key,id:item.id,name:item.name,price:item.price+m.price,qty:1,modifier:m,seat:seat||null}];})}
 const changeQty=(k,d)=>setCart(c=>c.map(x=>x.key===k?{...x,qty:x.qty+d}:x).filter(x=>x.qty>0)),removeCart=k=>setCart(c=>c.filter(x=>x.key!==k));
 function updateSeats(tableId,items){setTables(ts=>ts.map(t=>t.id!==tableId?t:{...t,seatState:t.seatState.map(s=>({...s,occupied:items.some(x=>Number(x.seat)===s.seat)}))}));}
 function placeOrder(){if(!cart.length||(channel==="Dine In"&&!selectedTable))return;const old=editingOrderId&&orders.find(o=>o.id===editingOrderId),r=reqs(cart),oldAlloc=old?.consumption||[],simulated=ingredients.map(i=>{const add=oldAlloc.filter(a=>a.ingredientId===i.id).reduce((s,a)=>s+a.qty,0);return {...i,stock:i.stock+add}}),{allocations,short}=planFIFO(r,simulated);if(short.length){alert("Insufficient stock: "+short.map(([id,q])=>{const i=ingredients.find(x=>x.id===id);return(i?.name||id)+" ("+q.toFixed(2)+" "+(i?.unit||"")+")"}).join(", "));return}const id=old?.id||"ORD-"+String(Date.now()).slice(-6),total=cart.reduce((s,x)=>s+x.price*x.qty,0),cogs=allocations.reduce((s,a)=>s+a.qty*a.cost,0),cust=customers.find(c=>String(c.id)===String(customerId)),now=new Date().toISOString();
 if(old){if(oldAlloc.length)restoreConsumption(oldAlloc,old.id);else{const fallback=planFIFO(reqs(old.items),ingredients).allocations;applyConsumption(fallback,1,"Sale Reversal",old.id)}applyConsumption(allocations,-1,"Sale",old.id);setOrders(os=>os.map(o=>o.id===old.id?{...o,channel,table:selectedTable?.name||null,tableId:selectedTable?.id||null,items:cart,total,cogs,consumption:allocations,customerId:cust?.id||null,customerName:cust?.name||null,updatedAt:now}:o));if(old.table&&old.table!==selectedTable?.name)setTables(ts=>ts.map(t=>t.name===old.table?{...t,status:"Vacant",orderId:null,seatState:t.seatState.map(s=>({...s,occupied:false}))}:t));if(selectedTable){setTables(ts=>ts.map(t=>t.id===selectedTable.id?{...t,status:"Order Placed",orderId:old.id}:t));updateSeats(selectedTable.id,cart)}}
 else{applyConsumption(allocations,-1,"Sale",id);setOrders(o=>[{id,channel,table:selectedTable?.name||null,tableId:selectedTable?.id||null,items:cart,total,cogs,consumption:allocations,customerId:cust?.id||null,customerName:cust?.name||null,status:orderStatuses[0],createdAt:now},...o]);if(selectedTable){setTables(ts=>ts.map(t=>t.id===selectedTable.id?{...t,status:"Order Placed",orderId:id}:t));updateSeats(selectedTable.id,cart)}}
 setCart([]);setSelectedTable(null);setCustomerId(null);setEditingOrderId(null);setActive("Orders")}
 function editOrder(o){if(o.status!=="Placed")return;setCart(o.items);setChannel(o.channel);setCustomerId(o.customerId||null);setEditingOrderId(o.id);setSelectedTable(tables.find(t=>t.id===o.tableId)||tables.find(t=>t.name===o.table)||null);setActive("POS")}
 const cancelEdit=()=>{setCart([]);setEditingOrderId(null);setSelectedTable(null);setCustomerId(null)};
 function updateOrder(id,status){const o=orders.find(x=>x.id===id);setOrders(os=>os.map(x=>x.id===id?{...x,status}:x));if(o?.table&&status===orderStatuses[3])setTables(ts=>ts.map(t=>t.name===o.table?{...t,status:"Dirty/Needs Cleaning",orderId:null,seatState:t.seatState.map(s=>({...s,occupied:false}))}:t));else if(o?.table&&status==="Ready")setTables(ts=>ts.map(t=>t.name===o.table?{...t,status:"Bill Printed",orderId:id}:t))}
 function transferOrder(o,t){if(o.channel!=="Dine In"||t.status!=="Vacant")return;setOrders(os=>os.map(x=>x.id===o.id?{...x,table:t.name,tableId:t.id}:x));setTables(ts=>ts.map(x=>x.id===t.id?{...x,status:"Order Placed",orderId:o.id,seatState:(x.seatState||[]).map(s=>({...s,occupied:false}))}:x.name===o.table?{...x,status:"Vacant",orderId:null,seatState:(x.seatState||[]).map(s=>({...s,occupied:false}))}:x));setTables(ts=>ts.map(x=>x.id===t.id?{...x,seatState:(x.seatState||[]).map(s=>({...s,occupied:(o.items||[]).some(i=>Number(i.seat)===s.seat)}))}:x))}
 function mergeTables(a,b){if(a.orderId&&b.orderId){alert("Both tables have active orders. Transfer one order first.");return}const group=a.mergedGroupId||b.mergedGroupId||"M"+Date.now();setTables(ts=>ts.map(t=>t.id===a.id||t.id===b.id?{...t,mergedGroupId:group,status:t.orderId?"Order Placed":"Seated"}:t))}
 function cleanTable(t){setTables(ts=>ts.map(x=>x.id===t.id?{...x,status:"Vacant",orderId:null,mergedGroupId:null,seatState:x.seatState.map(s=>({...s,occupied:false}))}:x))}
 function splitOrder(o,itemKey,qty){const item=o.items.find(x=>x.key===itemKey);if(!item||qty<=0||qty>=item.qty)return alert("Choose a quantity smaller than the selected line.");const moved={...item,qty},left={...item,qty:item.qty-qty},ratio=qty/item.qty,id="ORD-"+String(Date.now()).slice(-6),movedConsumption=(o.consumption||[]).map(a=>({...a,qty:a.qty*ratio})),leftConsumption=(o.consumption||[]).map(a=>({...a,qty:a.qty*(1-ratio)}));setOrders(os=>os.map(v=>v.id===o.id?{...v,items:v.items.map(x=>x.key===itemKey?left:x),total:v.total-moved.price*qty,cogs:leftConsumption.reduce((s,a)=>s+a.qty*a.cost,0),consumption:leftConsumption}:v).concat({...o,id,items:[moved],total:moved.price*qty,cogs:movedConsumption.reduce((s,a)=>s+a.qty*a.cost,0),consumption:movedConsumption,parentOrderId:o.id,splitBill:true,createdAt:new Date().toISOString()}))}
 function voidOrder(id){const o=orders.find(x=>x.id===id);if(!o||o.status==="Voided")return;if(!window.confirm("Void "+o.id+"? This will reverse its inventory consumption."))return;if(o.consumption?.length)restoreConsumption(o.consumption,o.id);setOrders(os=>os.map(x=>x.id===id?{...x,status:"Voided",voidedAt:new Date().toISOString()}:x));if(o.tableId)setTables(ts=>ts.map(t=>t.id===o.tableId?{...t,status:"Vacant",orderId:null,seatState:(t.seatState||[]).map(s=>({...s,occupied:false}))}:t))}
 const openTable=t=>{if(t.status==="Vacant"){setSelectedTable(t);setChannel("Dine In");setActive("POS")}else if(t.status==="Dirty/Needs Cleaning")cleanTable(t)};
 return <div className="app"><Sidebar collapsed={collapsed} setCollapsed={setCollapsed} active={active} setActive={setActive}/><main className="main"><Topbar active={active}/>
 {active==="Dashboard"&&<Dashboard money={money} sales={todaySales} openOrders={openOrders} occupied={occupied} lowStock={lowStock} orders={orders} tables={tables} onPOS={()=>setActive("POS")}/>}
 {active==="POS"&&<POS menu={menu} categories={categories} modifiers={modifiers} cart={cart} addItem={addItem} changeQty={changeQty} removeCart={removeCart} placeOrder={placeOrder} channel={channel} setChannel={setChannel} selectedTable={selectedTable} setSelectedTable={setSelectedTable} tables={tables} money={money} customers={customers} customerId={customerId} setCustomerId={setCustomerId} editingOrderId={editingOrderId} cancelEdit={cancelEdit}/>}
 {active==="Tables"&&<Tables tables={tables} onTable={openTable} onMerge={mergeTables} onTransfer={(a,id)=>{const t=tables.find(x=>x.id===id),o=orders.find(x=>x.id===a.orderId);if(t&&o)transferOrder(o,t)}} onClean={cleanTable} tableStatuses={tableStatuses}/>}
 {active==="Orders"&&<Orders orders={orders} update={updateOrder} money={money} onEdit={editOrder} onSplit={splitOrder} onVoid={voidOrder} onTransfer={o=>{const n=prompt("Transfer "+o.id+" to table (e.g. T5):");const t=tables.find(x=>x.name.toLowerCase()===(n||"").trim().toLowerCase()&&x.status==="Vacant");if(t)transferOrder(o,t);else if(n)alert("That table is not vacant or does not exist.")}}/>}
 {active==="Kitchen"&&<Kitchen orders={orders} update={updateOrder} money={money}/>}
 {active==="Delivery"&&<Delivery orders={orders} update={updateOrder} money={money} riders={riders} setRiders={setRiders} riderStatuses={riderStatuses} setOrders={setOrders}/>}
 {active==="Menu"&&<MenuManager menu={menu} setMenu={setMenu} categories={categories} money={money}/>}
 {active==="Inventory"&&<Inventory ingredients={ingredients} setIngredients={setIngredients} movements={movements} setMovements={setMovements} money={money}/>}
 {active==="Payments"&&<Payments orders={orders} payments={payments} setPayments={setPayments} setOrders={setOrders} money={money}/>}
 {active==="Complaints"&&<Complaints orders={orders} complaints={complaints} setComplaints={setComplaints} adjustments={adjustments} setAdjustments={setAdjustments} types={complaintTypes} statuses={complaintStatuses} resolutions={resolutions} money={money}/>}
 {active==="Analytics"&&<Analytics orders={orders} menu={menu} recipes={recipes} ingredients={ingredients} movements={movements} adjustments={adjustments}/>}
 {active==="Staff"&&<Staff staff={staff} setStaff={setStaff} roles={staffRoles}/>}
 {active==="Staff Performance"&&<StaffPerformance staff={staff} shifts={shifts} setShifts={setShifts} orders={orders} complaints={complaints}/>}
 {active==="Customers"&&<Customers customers={customers} setCustomers={setCustomers} types={customerTypes}/>}
 {![ "Dashboard","POS","Tables","Orders","Kitchen","Delivery","Menu","Inventory","Payments","Complaints","Analytics","Staff","Staff Performance","Customers"].includes(active)&&<ModulePreview name={active}/>}
 </main></div>}
function ModulePreview({name}){return <section className="content"><div className="module"><div className="module-icon"><Settings size={28}/></div><h2>{name}</h2><p>This module is connected to the shared POS data model. Its dedicated workflow is next in the build.</p></div></section>}